apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo_task_app_deploy
  labels:
    app: todo_task_app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo_task_app
  template:
    metadata:
      labels:
        app: todo_task_app
    spec:
      containers:
      - name: todo_task_app-server
        image: praveenselvakumarasamy/todo_task_app:latest
        ports:
        - containerPort: 8080
