apiVersion: v1
kind: Service
metadata:
  name: todo_task_app_service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: todo_task_app
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8080
      nodeport: 30600
      