apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-task-app
  labels:
    app: todo-task-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-task-app
  template:
    metadata:
      labels:
        app: todo-task-app
    spec:
      containers:
      - name: todo-task-app
        image: praveenselvakumarasamy/todo_task_app:latest
        ports:
        - containerPort: 8080
