apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-task-app-deploy
  labels:
    app: todo-task-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-task-app
  template:
    metadata:
      labels:
        app: todo-task-app
    spec:
      containers:
      - name: todo-task-app-server
        image: praveenselvakumarasamy/todo_task_app:latest
        ports:
        - containerPort: 8080
