apiVersion: v1
kind: Service
metadata:
  name: todo-task-app-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: todo-task-app
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8080
      nodeport: 30600
      